deployment_name: concourse-staging
external_url: https://ci.fr-stage.cloud.gov
credhub_url: https://credhub.fr-stage.cloud.gov
azs: [z2]
web_vm_type: t3.medium.concourse.web
worker_vm_type: m5.xlarge.concourse.worker
iaas_worker_vm_type: m5.xlarge.concourse.worker
web_vm_extensions: [staging-concourse-lb]
worker_vm_extensions: [staging-concourse-profile]
iaas_worker_vm_extensions: [staging-concourse-iaas-profile]
network_name: staging-concourse
web_instances: 1
worker_instances: 2
iaas_worker_instances: 1
build_logs_default: 25
build_logs_maximum: 0
max_active_containers_per_worker: 100
